/**
 * Generate the MCP server instructions from the Executor app's `executor` skill, so the skill stays
 * their only source. Hosts on every runtime import the result; Workers cannot read the file.
 * Pass --check to fail when the generated module is stale.
 */
import * as NodeRuntime from "@effect/platform-node/NodeRuntime";
import * as NodeServices from "@effect/platform-node/NodeServices";
import { Effect, FileSystem, Path, Schema } from "effect";

class ExecutorIntroInvalid extends Schema.TaggedError<ExecutorIntroInvalid>()(
  "ExecutorIntroInvalid",
  { reason: Schema.String },
) {
  override get message() {
    return this.reason;
  }
}

NodeRuntime.runMain(
  Effect.gen(function* () {
    const fs = yield* FileSystem.FileSystem;
    const path = yield* Path.Path;
    const root = yield* path.fromFileUrl(new URL("../", import.meta.url));
    const skill = yield* fs.readFileString(path.join(root, "executor/skills/executor/SKILL.md"));
    const body = /^---\n[\s\S]*?\n---\n([\s\S]+)$/.exec(skill)?.[1]?.trim();
    if (body === undefined || body === "")
      return yield* new ExecutorIntroInvalid({
        reason: "skills/executor/SKILL.md needs YAML frontmatter followed by a body.",
      });
    const generated = `// Generated by packages/app-templates/scripts/executor-intro.ts. Do not edit.

/** The body of skills/executor/SKILL.md, without its frontmatter. MCP servers send it as their instructions. */
export const executorIntro = ${JSON.stringify(body)};
`;
    const output = path.join(root, "src/implementation/executor-intro.gen.ts");
    if (!process.argv.includes("--check")) return yield* fs.writeFileString(output, generated);
    const current = yield* fs.readFileString(output).pipe(Effect.orElseSucceed(() => ""));
    if (current !== generated)
      return yield* new ExecutorIntroInvalid({
        reason: "executor-intro.gen.ts is stale. Run: bun run executor:intro",
      });
  }).pipe(Effect.provide(NodeServices.layer)),
);
