/**
 * Generate the MCP server instructions from the Executor app's `executor` skill, so the skill stays
 * their only source, and the digests telemetry uses to recognize the app's published skill files.
 * Hosts on every runtime import the results; Workers cannot read the files.
 * Pass --check to fail when a generated module is stale. Either way it fails when the skill names
 * an MCP SDK version other than the one `apps` is built with, which quick add pins.
 */
import * as NodeRuntime from "@effect/platform-node/NodeRuntime";
import * as NodeServices from "@effect/platform-node/NodeServices";
import { Crypto, Effect, FileSystem, Path, Schema } from "effect";
import { Hex } from "effect/encoding";
import apps from "apps/package.json" with { type: "json" };
import { readExecutorSkillDocuments } from "../src/implementation/executor-skills.ts";

class ExecutorIntroInvalid extends Schema.TaggedError<ExecutorIntroInvalid>()(
  "ExecutorIntroInvalid",
  { reason: Schema.String },
) {
  override get message() {
    return this.reason;
  }
}

const header = "// Generated by packages/app-templates/scripts/executor-intro.ts. Do not edit.";

NodeRuntime.runMain(
  Effect.gen(function* () {
    const fs = yield* FileSystem.FileSystem;
    const path = yield* Path.Path;
    const crypto = yield* Crypto.Crypto;
    const root = yield* path.fromFileUrl(new URL("../", import.meta.url));
    const skill = yield* fs.readFileString(path.join(root, "executor/skills/executor/SKILL.md"));
    const body = /^---\n[\s\S]*?\n---\n([\s\S]+)$/.exec(skill)?.[1]?.trim();
    if (body === undefined || body === "")
      return yield* new ExecutorIntroInvalid({
        reason: "skills/executor/SKILL.md needs YAML frontmatter followed by a body.",
      });
    const sdk = apps.devDependencies["@modelcontextprotocol/sdk"];
    const integrations = yield* fs.readFileString(
      path.join(root, "executor/skills/app-authoring/integrations.md"),
    );
    if (/`@modelcontextprotocol\/sdk` \(currently\s+`([^`]+)`\)/.exec(integrations)?.[1] !== sdk)
      return yield* new ExecutorIntroInvalid({
        reason: `skills/app-authoring/integrations.md must name @modelcontextprotocol/sdk as (currently \`${sdk}\`), the version apps is built with.`,
      });
    // The same files the hosts publish, keyed as a skill document names them.
    const digests = yield* Effect.forEach(
      // Code-point order, so the output does not depend on the machine's locale.
      [...(yield* readExecutorSkillDocuments)].sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0)),
      ([file, content]) =>
        crypto
          .digest("SHA-256", new TextEncoder().encode(content))
          .pipe(Effect.map((digest) => [file.replace(/^skills\//, ""), Hex.encode(digest)])),
    );
    const outputs = [
      {
        file: "executor-intro.gen.ts",
        content: `${header}

/** The body of skills/executor/SKILL.md, without its frontmatter. MCP servers send it as their instructions. */
export const executorIntro = ${JSON.stringify(body)};
`,
      },
      {
        file: "executor-skill-digests.gen.ts",
        content: `${header}

/** SHA-256 of each file the Executor app publishes as a skill, keyed by \`<skill>/<file>\`. */
export const executorSkillDigests: Readonly<Record<string, string>> = ${JSON.stringify(Object.fromEntries(digests), null, 2)};
`,
      },
    ];
    for (const { file, content } of outputs) {
      const output = path.join(root, "src/implementation", file);
      if (!process.argv.includes("--check")) {
        yield* fs.writeFileString(output, content);
        continue;
      }
      const current = yield* fs.readFileString(output).pipe(Effect.orElseSucceed(() => ""));
      if (current !== content)
        return yield* new ExecutorIntroInvalid({
          reason: `${file} is stale. Run: bun run executor:intro`,
        });
    }
  }).pipe(Effect.provide(NodeServices.layer)),
);
