/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AppAuthRouteImport } from './routes/app-auth'
import { Route as CreateRouteImport } from './routes/create'
import { Route as DeviceRouteImport } from './routes/device'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AccountProfileRouteImport } from './routes/account.profile'
import { Route as AccountSecurityRouteImport } from './routes/account.security'
import { Route as AccountTokensRouteImport } from './routes/account.tokens'
import { Route as CreateAgentRouteImport } from './routes/create_.agent'
import { Route as EmailUnsubscribeRouteImport } from './routes/email.unsubscribe'
import { Route as LoginSsoRouteImport } from './routes/login_.sso'
import { Route as McpAuthorizeRouteImport } from './routes/mcp.authorize'
import { Route as OauthCallbackRouteImport } from './routes/oauth.callback'
import { Route as OrgOrganizationSlugRouteImport } from './routes/org.$organizationSlug'
import { Route as McpApproveRequestIdRouteImport } from './routes/mcp.approve.$requestId'
import { Route as OrgOrganizationSlugIndexRouteImport } from './routes/org.$organizationSlug.index'
import { Route as OrgOrganizationSlugApiKeysRouteImport } from './routes/org.$organizationSlug.api-keys'
import { Route as OrgOrganizationSlugBillingRouteImport } from './routes/org.$organizationSlug.billing'
import { Route as OrgOrganizationSlugConnectRouteImport } from './routes/org.$organizationSlug.connect'
import { Route as OrgOrganizationSlugOrganizationRouteImport } from './routes/org.$organizationSlug.organization'
import { Route as OrgOrganizationSlugAccountsIndexRouteImport } from './routes/org.$organizationSlug.accounts.index'
import { Route as OrgOrganizationSlugApprovalsIndexRouteImport } from './routes/org.$organizationSlug.approvals.index'
import { Route as OrgOrganizationSlugApprovalsRunIdRouteImport } from './routes/org.$organizationSlug.approvals.$runId'
import { Route as OrgOrganizationSlugAppsIndexRouteImport } from './routes/org.$organizationSlug.apps.index'
import { Route as OrgOrganizationSlugAppsAppIdRouteImport } from './routes/org.$organizationSlug.apps.$appId'
import { Route as OrgOrganizationSlugConnectionsConnectionIdRouteImport } from './routes/org.$organizationSlug.connections.$connectionId'
import { Route as OrgOrganizationSlugGroupsIndexRouteImport } from './routes/org.$organizationSlug.groups.index'
import { Route as OrgOrganizationSlugGroupsGroupIdRouteImport } from './routes/org.$organizationSlug.groups.$groupId'
import { Route as OrgOrganizationSlugAppsAppIdOpenRouteImport } from './routes/org.$organizationSlug.apps.$appId_.open'
import { Route as OrgOrganizationSlugAppsAppIdSetupRouteImport } from './routes/org.$organizationSlug.apps.$appId_.setup'
import { Route as OrgOrganizationSlugAppsAddIndexRouteImport } from './routes/org.$organizationSlug.apps.add.index'
import { Route as OrgOrganizationSlugAppsAddCustomRouteImport } from './routes/org.$organizationSlug.apps.add.custom'
import { Route as OrgOrganizationSlugWebhooksAppIdSubscriptionIdRouteImport } from './routes/org.$organizationSlug.webhooks.$appId.$subscriptionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthRoute = AppAuthRouteImport.update({
  id: '/app-auth',
  path: '/app-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceRoute = DeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRoute,
} as any)
const AccountSecurityRoute = AccountSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AccountRoute,
} as any)
const AccountTokensRoute = AccountTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => AccountRoute,
} as any)
const CreateAgentRoute = CreateAgentRouteImport.update({
  id: '/create_/agent',
  path: '/create/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginSsoRoute = LoginSsoRouteImport.update({
  id: '/login_/sso',
  path: '/login/sso',
  getParentRoute: () => rootRouteImport,
} as any)
const McpAuthorizeRoute = McpAuthorizeRouteImport.update({
  id: '/mcp/authorize',
  path: '/mcp/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgOrganizationSlugRoute = OrgOrganizationSlugRouteImport.update({
  id: '/org/$organizationSlug',
  path: '/org/$organizationSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const McpApproveRequestIdRoute = McpApproveRequestIdRouteImport.update({
  id: '/mcp/approve/$requestId',
  path: '/mcp/approve/$requestId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgOrganizationSlugIndexRoute =
  OrgOrganizationSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrgOrganizationSlugRoute,
  } as any)
const OrgOrganizationSlugApiKeysRoute =
  OrgOrganizationSlugApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => OrgOrganizationSlugRoute,
  } as any)
const OrgOrganizationSlugBillingRoute =
  OrgOrganizationSlugBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => OrgOrganizationSlugRoute,
  } as any)
const OrgOrganizationSlugConnectRoute =
  OrgOrganizationSlugConnectRouteImport.update({
    id: '/connect',
    path: '/connect',
    getParentRoute: () => OrgOrganizationSlugRoute,
  } as any)
const OrgOrganizationSlugOrganizationRoute =
  OrgOrganizationSlugOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => OrgOrganizationSlugRoute,
  } as any)
const OrgOrganizationSlugAccountsIndexRoute =
  OrgOrganizationSlugAccountsIndexRouteImport.update({
    id: '/accounts/',
    path: '/accounts/',
    getParentRoute: () => OrgOrganizationSlugRoute,
  } as any)
const OrgOrganizationSlugApprovalsIndexRoute =
  OrgOrganizationSlugApprovalsIndexRouteImport.update({
    id: '/approvals/',
    path: '/approvals/',
    getParentRoute: () => OrgOrganizationSlugRoute,
  } as any)
const OrgOrganizationSlugApprovalsRunIdRoute =
  OrgOrganizationSlugApprovalsRunIdRouteImport.update({
    id: '/approvals/$runId',
    path: '/approvals/$runId',
    getParentRoute: () => OrgOrganizationSlugRoute,
  } as any)
const OrgOrganizationSlugAppsIndexRoute =
  OrgOrganizationSlugAppsIndexRouteImport.update({
    id: '/apps/',
    path: '/apps/',
    getParentRoute: () => OrgOrganizationSlugRoute,
  } as any)
const OrgOrganizationSlugAppsAppIdRoute =
  OrgOrganizationSlugAppsAppIdRouteImport.update({
    id: '/apps/$appId',
    path: '/apps/$appId',
    getParentRoute: () => OrgOrganizationSlugRoute,
  } as any)
const OrgOrganizationSlugConnectionsConnectionIdRoute =
  OrgOrganizationSlugConnectionsConnectionIdRouteImport.update({
    id: '/connections/$connectionId',
    path: '/connections/$connectionId',
    getParentRoute: () => OrgOrganizationSlugRoute,
  } as any)
const OrgOrganizationSlugGroupsIndexRoute =
  OrgOrganizationSlugGroupsIndexRouteImport.update({
    id: '/groups/',
    path: '/groups/',
    getParentRoute: () => OrgOrganizationSlugRoute,
  } as any)
const OrgOrganizationSlugGroupsGroupIdRoute =
  OrgOrganizationSlugGroupsGroupIdRouteImport.update({
    id: '/groups/$groupId',
    path: '/groups/$groupId',
    getParentRoute: () => OrgOrganizationSlugRoute,
  } as any)
const OrgOrganizationSlugAppsAppIdOpenRoute =
  OrgOrganizationSlugAppsAppIdOpenRouteImport.update({
    id: '/apps/$appId_/open',
    path: '/apps/$appId/open',
    getParentRoute: () => OrgOrganizationSlugRoute,
  } as any)
const OrgOrganizationSlugAppsAppIdSetupRoute =
  OrgOrganizationSlugAppsAppIdSetupRouteImport.update({
    id: '/apps/$appId_/setup',
    path: '/apps/$appId/setup',
    getParentRoute: () => OrgOrganizationSlugRoute,
  } as any)
const OrgOrganizationSlugAppsAddIndexRoute =
  OrgOrganizationSlugAppsAddIndexRouteImport.update({
    id: '/apps/add/',
    path: '/apps/add/',
    getParentRoute: () => OrgOrganizationSlugRoute,
  } as any)
const OrgOrganizationSlugAppsAddCustomRoute =
  OrgOrganizationSlugAppsAddCustomRouteImport.update({
    id: '/apps/add/custom',
    path: '/apps/add/custom',
    getParentRoute: () => OrgOrganizationSlugRoute,
  } as any)
const OrgOrganizationSlugWebhooksAppIdSubscriptionIdRoute =
  OrgOrganizationSlugWebhooksAppIdSubscriptionIdRouteImport.update({
    id: '/webhooks/$appId/$subscriptionId',
    path: '/webhooks/$appId/$subscriptionId',
    getParentRoute: () => OrgOrganizationSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/app-auth': typeof AppAuthRoute
  '/create': typeof CreateRoute
  '/device': typeof DeviceRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/tokens': typeof AccountTokensRoute
  '/create/agent': typeof CreateAgentRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/login/sso': typeof LoginSsoRoute
  '/mcp/authorize': typeof McpAuthorizeRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/org/$organizationSlug': typeof OrgOrganizationSlugRouteWithChildren
  '/account/': typeof AccountIndexRoute
  '/mcp/approve/$requestId': typeof McpApproveRequestIdRoute
  '/org/$organizationSlug/api-keys': typeof OrgOrganizationSlugApiKeysRoute
  '/org/$organizationSlug/billing': typeof OrgOrganizationSlugBillingRoute
  '/org/$organizationSlug/connect': typeof OrgOrganizationSlugConnectRoute
  '/org/$organizationSlug/organization': typeof OrgOrganizationSlugOrganizationRoute
  '/org/$organizationSlug/': typeof OrgOrganizationSlugIndexRoute
  '/org/$organizationSlug/approvals/$runId': typeof OrgOrganizationSlugApprovalsRunIdRoute
  '/org/$organizationSlug/apps/$appId': typeof OrgOrganizationSlugAppsAppIdRoute
  '/org/$organizationSlug/connections/$connectionId': typeof OrgOrganizationSlugConnectionsConnectionIdRoute
  '/org/$organizationSlug/groups/$groupId': typeof OrgOrganizationSlugGroupsGroupIdRoute
  '/org/$organizationSlug/accounts/': typeof OrgOrganizationSlugAccountsIndexRoute
  '/org/$organizationSlug/approvals/': typeof OrgOrganizationSlugApprovalsIndexRoute
  '/org/$organizationSlug/apps/': typeof OrgOrganizationSlugAppsIndexRoute
  '/org/$organizationSlug/groups/': typeof OrgOrganizationSlugGroupsIndexRoute
  '/org/$organizationSlug/apps/$appId/open': typeof OrgOrganizationSlugAppsAppIdOpenRoute
  '/org/$organizationSlug/apps/$appId/setup': typeof OrgOrganizationSlugAppsAppIdSetupRoute
  '/org/$organizationSlug/apps/add/custom': typeof OrgOrganizationSlugAppsAddCustomRoute
  '/org/$organizationSlug/webhooks/$appId/$subscriptionId': typeof OrgOrganizationSlugWebhooksAppIdSubscriptionIdRoute
  '/org/$organizationSlug/apps/add/': typeof OrgOrganizationSlugAppsAddIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app-auth': typeof AppAuthRoute
  '/create': typeof CreateRoute
  '/device': typeof DeviceRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/tokens': typeof AccountTokensRoute
  '/create/agent': typeof CreateAgentRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/login/sso': typeof LoginSsoRoute
  '/mcp/authorize': typeof McpAuthorizeRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/account': typeof AccountIndexRoute
  '/mcp/approve/$requestId': typeof McpApproveRequestIdRoute
  '/org/$organizationSlug/api-keys': typeof OrgOrganizationSlugApiKeysRoute
  '/org/$organizationSlug/billing': typeof OrgOrganizationSlugBillingRoute
  '/org/$organizationSlug/connect': typeof OrgOrganizationSlugConnectRoute
  '/org/$organizationSlug/organization': typeof OrgOrganizationSlugOrganizationRoute
  '/org/$organizationSlug': typeof OrgOrganizationSlugIndexRoute
  '/org/$organizationSlug/approvals/$runId': typeof OrgOrganizationSlugApprovalsRunIdRoute
  '/org/$organizationSlug/apps/$appId': typeof OrgOrganizationSlugAppsAppIdRoute
  '/org/$organizationSlug/connections/$connectionId': typeof OrgOrganizationSlugConnectionsConnectionIdRoute
  '/org/$organizationSlug/groups/$groupId': typeof OrgOrganizationSlugGroupsGroupIdRoute
  '/org/$organizationSlug/accounts': typeof OrgOrganizationSlugAccountsIndexRoute
  '/org/$organizationSlug/approvals': typeof OrgOrganizationSlugApprovalsIndexRoute
  '/org/$organizationSlug/apps': typeof OrgOrganizationSlugAppsIndexRoute
  '/org/$organizationSlug/groups': typeof OrgOrganizationSlugGroupsIndexRoute
  '/org/$organizationSlug/apps/$appId/open': typeof OrgOrganizationSlugAppsAppIdOpenRoute
  '/org/$organizationSlug/apps/$appId/setup': typeof OrgOrganizationSlugAppsAppIdSetupRoute
  '/org/$organizationSlug/apps/add/custom': typeof OrgOrganizationSlugAppsAddCustomRoute
  '/org/$organizationSlug/webhooks/$appId/$subscriptionId': typeof OrgOrganizationSlugWebhooksAppIdSubscriptionIdRoute
  '/org/$organizationSlug/apps/add': typeof OrgOrganizationSlugAppsAddIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/app-auth': typeof AppAuthRoute
  '/create': typeof CreateRoute
  '/device': typeof DeviceRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/tokens': typeof AccountTokensRoute
  '/create_/agent': typeof CreateAgentRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/login_/sso': typeof LoginSsoRoute
  '/mcp/authorize': typeof McpAuthorizeRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/org/$organizationSlug': typeof OrgOrganizationSlugRouteWithChildren
  '/account/': typeof AccountIndexRoute
  '/mcp/approve/$requestId': typeof McpApproveRequestIdRoute
  '/org/$organizationSlug/api-keys': typeof OrgOrganizationSlugApiKeysRoute
  '/org/$organizationSlug/billing': typeof OrgOrganizationSlugBillingRoute
  '/org/$organizationSlug/connect': typeof OrgOrganizationSlugConnectRoute
  '/org/$organizationSlug/organization': typeof OrgOrganizationSlugOrganizationRoute
  '/org/$organizationSlug/': typeof OrgOrganizationSlugIndexRoute
  '/org/$organizationSlug/approvals/$runId': typeof OrgOrganizationSlugApprovalsRunIdRoute
  '/org/$organizationSlug/apps/$appId': typeof OrgOrganizationSlugAppsAppIdRoute
  '/org/$organizationSlug/connections/$connectionId': typeof OrgOrganizationSlugConnectionsConnectionIdRoute
  '/org/$organizationSlug/groups/$groupId': typeof OrgOrganizationSlugGroupsGroupIdRoute
  '/org/$organizationSlug/accounts/': typeof OrgOrganizationSlugAccountsIndexRoute
  '/org/$organizationSlug/approvals/': typeof OrgOrganizationSlugApprovalsIndexRoute
  '/org/$organizationSlug/apps/': typeof OrgOrganizationSlugAppsIndexRoute
  '/org/$organizationSlug/groups/': typeof OrgOrganizationSlugGroupsIndexRoute
  '/org/$organizationSlug/apps/$appId_/open': typeof OrgOrganizationSlugAppsAppIdOpenRoute
  '/org/$organizationSlug/apps/$appId_/setup': typeof OrgOrganizationSlugAppsAppIdSetupRoute
  '/org/$organizationSlug/apps/add/custom': typeof OrgOrganizationSlugAppsAddCustomRoute
  '/org/$organizationSlug/webhooks/$appId/$subscriptionId': typeof OrgOrganizationSlugWebhooksAppIdSubscriptionIdRoute
  '/org/$organizationSlug/apps/add/': typeof OrgOrganizationSlugAppsAddIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/app-auth'
    | '/create'
    | '/device'
    | '/invite'
    | '/login'
    | '/account/profile'
    | '/account/security'
    | '/account/tokens'
    | '/create/agent'
    | '/email/unsubscribe'
    | '/login/sso'
    | '/mcp/authorize'
    | '/oauth/callback'
    | '/org/$organizationSlug'
    | '/account/'
    | '/mcp/approve/$requestId'
    | '/org/$organizationSlug/api-keys'
    | '/org/$organizationSlug/billing'
    | '/org/$organizationSlug/connect'
    | '/org/$organizationSlug/organization'
    | '/org/$organizationSlug/'
    | '/org/$organizationSlug/approvals/$runId'
    | '/org/$organizationSlug/apps/$appId'
    | '/org/$organizationSlug/connections/$connectionId'
    | '/org/$organizationSlug/groups/$groupId'
    | '/org/$organizationSlug/accounts/'
    | '/org/$organizationSlug/approvals/'
    | '/org/$organizationSlug/apps/'
    | '/org/$organizationSlug/groups/'
    | '/org/$organizationSlug/apps/$appId/open'
    | '/org/$organizationSlug/apps/$appId/setup'
    | '/org/$organizationSlug/apps/add/custom'
    | '/org/$organizationSlug/webhooks/$appId/$subscriptionId'
    | '/org/$organizationSlug/apps/add/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app-auth'
    | '/create'
    | '/device'
    | '/invite'
    | '/login'
    | '/account/profile'
    | '/account/security'
    | '/account/tokens'
    | '/create/agent'
    | '/email/unsubscribe'
    | '/login/sso'
    | '/mcp/authorize'
    | '/oauth/callback'
    | '/account'
    | '/mcp/approve/$requestId'
    | '/org/$organizationSlug/api-keys'
    | '/org/$organizationSlug/billing'
    | '/org/$organizationSlug/connect'
    | '/org/$organizationSlug/organization'
    | '/org/$organizationSlug'
    | '/org/$organizationSlug/approvals/$runId'
    | '/org/$organizationSlug/apps/$appId'
    | '/org/$organizationSlug/connections/$connectionId'
    | '/org/$organizationSlug/groups/$groupId'
    | '/org/$organizationSlug/accounts'
    | '/org/$organizationSlug/approvals'
    | '/org/$organizationSlug/apps'
    | '/org/$organizationSlug/groups'
    | '/org/$organizationSlug/apps/$appId/open'
    | '/org/$organizationSlug/apps/$appId/setup'
    | '/org/$organizationSlug/apps/add/custom'
    | '/org/$organizationSlug/webhooks/$appId/$subscriptionId'
    | '/org/$organizationSlug/apps/add'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/app-auth'
    | '/create'
    | '/device'
    | '/invite'
    | '/login'
    | '/account/profile'
    | '/account/security'
    | '/account/tokens'
    | '/create_/agent'
    | '/email/unsubscribe'
    | '/login_/sso'
    | '/mcp/authorize'
    | '/oauth/callback'
    | '/org/$organizationSlug'
    | '/account/'
    | '/mcp/approve/$requestId'
    | '/org/$organizationSlug/api-keys'
    | '/org/$organizationSlug/billing'
    | '/org/$organizationSlug/connect'
    | '/org/$organizationSlug/organization'
    | '/org/$organizationSlug/'
    | '/org/$organizationSlug/approvals/$runId'
    | '/org/$organizationSlug/apps/$appId'
    | '/org/$organizationSlug/connections/$connectionId'
    | '/org/$organizationSlug/groups/$groupId'
    | '/org/$organizationSlug/accounts/'
    | '/org/$organizationSlug/approvals/'
    | '/org/$organizationSlug/apps/'
    | '/org/$organizationSlug/groups/'
    | '/org/$organizationSlug/apps/$appId_/open'
    | '/org/$organizationSlug/apps/$appId_/setup'
    | '/org/$organizationSlug/apps/add/custom'
    | '/org/$organizationSlug/webhooks/$appId/$subscriptionId'
    | '/org/$organizationSlug/apps/add/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  AppAuthRoute: typeof AppAuthRoute
  CreateRoute: typeof CreateRoute
  DeviceRoute: typeof DeviceRoute
  InviteRoute: typeof InviteRoute
  LoginRoute: typeof LoginRoute
  CreateAgentRoute: typeof CreateAgentRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  LoginSsoRoute: typeof LoginSsoRoute
  McpAuthorizeRoute: typeof McpAuthorizeRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  OrgOrganizationSlugRoute: typeof OrgOrganizationSlugRouteWithChildren
  McpApproveRequestIdRoute: typeof McpApproveRequestIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-auth': {
      id: '/app-auth'
      path: '/app-auth'
      fullPath: '/app-auth'
      preLoaderRoute: typeof AppAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device': {
      id: '/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/security': {
      id: '/account/security'
      path: '/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AccountSecurityRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/tokens': {
      id: '/account/tokens'
      path: '/tokens'
      fullPath: '/account/tokens'
      preLoaderRoute: typeof AccountTokensRouteImport
      parentRoute: typeof AccountRoute
    }
    '/create_/agent': {
      id: '/create_/agent'
      path: '/create/agent'
      fullPath: '/create/agent'
      preLoaderRoute: typeof CreateAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login_/sso': {
      id: '/login_/sso'
      path: '/login/sso'
      fullPath: '/login/sso'
      preLoaderRoute: typeof LoginSsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp/authorize': {
      id: '/mcp/authorize'
      path: '/mcp/authorize'
      fullPath: '/mcp/authorize'
      preLoaderRoute: typeof McpAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$organizationSlug': {
      id: '/org/$organizationSlug'
      path: '/org/$organizationSlug'
      fullPath: '/org/$organizationSlug'
      preLoaderRoute: typeof OrgOrganizationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp/approve/$requestId': {
      id: '/mcp/approve/$requestId'
      path: '/mcp/approve/$requestId'
      fullPath: '/mcp/approve/$requestId'
      preLoaderRoute: typeof McpApproveRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$organizationSlug/': {
      id: '/org/$organizationSlug/'
      path: '/'
      fullPath: '/org/$organizationSlug/'
      preLoaderRoute: typeof OrgOrganizationSlugIndexRouteImport
      parentRoute: typeof OrgOrganizationSlugRoute
    }
    '/org/$organizationSlug/api-keys': {
      id: '/org/$organizationSlug/api-keys'
      path: '/api-keys'
      fullPath: '/org/$organizationSlug/api-keys'
      preLoaderRoute: typeof OrgOrganizationSlugApiKeysRouteImport
      parentRoute: typeof OrgOrganizationSlugRoute
    }
    '/org/$organizationSlug/billing': {
      id: '/org/$organizationSlug/billing'
      path: '/billing'
      fullPath: '/org/$organizationSlug/billing'
      preLoaderRoute: typeof OrgOrganizationSlugBillingRouteImport
      parentRoute: typeof OrgOrganizationSlugRoute
    }
    '/org/$organizationSlug/connect': {
      id: '/org/$organizationSlug/connect'
      path: '/connect'
      fullPath: '/org/$organizationSlug/connect'
      preLoaderRoute: typeof OrgOrganizationSlugConnectRouteImport
      parentRoute: typeof OrgOrganizationSlugRoute
    }
    '/org/$organizationSlug/organization': {
      id: '/org/$organizationSlug/organization'
      path: '/organization'
      fullPath: '/org/$organizationSlug/organization'
      preLoaderRoute: typeof OrgOrganizationSlugOrganizationRouteImport
      parentRoute: typeof OrgOrganizationSlugRoute
    }
    '/org/$organizationSlug/accounts/': {
      id: '/org/$organizationSlug/accounts/'
      path: '/accounts'
      fullPath: '/org/$organizationSlug/accounts/'
      preLoaderRoute: typeof OrgOrganizationSlugAccountsIndexRouteImport
      parentRoute: typeof OrgOrganizationSlugRoute
    }
    '/org/$organizationSlug/approvals/': {
      id: '/org/$organizationSlug/approvals/'
      path: '/approvals'
      fullPath: '/org/$organizationSlug/approvals/'
      preLoaderRoute: typeof OrgOrganizationSlugApprovalsIndexRouteImport
      parentRoute: typeof OrgOrganizationSlugRoute
    }
    '/org/$organizationSlug/approvals/$runId': {
      id: '/org/$organizationSlug/approvals/$runId'
      path: '/approvals/$runId'
      fullPath: '/org/$organizationSlug/approvals/$runId'
      preLoaderRoute: typeof OrgOrganizationSlugApprovalsRunIdRouteImport
      parentRoute: typeof OrgOrganizationSlugRoute
    }
    '/org/$organizationSlug/apps/': {
      id: '/org/$organizationSlug/apps/'
      path: '/apps'
      fullPath: '/org/$organizationSlug/apps/'
      preLoaderRoute: typeof OrgOrganizationSlugAppsIndexRouteImport
      parentRoute: typeof OrgOrganizationSlugRoute
    }
    '/org/$organizationSlug/apps/$appId': {
      id: '/org/$organizationSlug/apps/$appId'
      path: '/apps/$appId'
      fullPath: '/org/$organizationSlug/apps/$appId'
      preLoaderRoute: typeof OrgOrganizationSlugAppsAppIdRouteImport
      parentRoute: typeof OrgOrganizationSlugRoute
    }
    '/org/$organizationSlug/connections/$connectionId': {
      id: '/org/$organizationSlug/connections/$connectionId'
      path: '/connections/$connectionId'
      fullPath: '/org/$organizationSlug/connections/$connectionId'
      preLoaderRoute: typeof OrgOrganizationSlugConnectionsConnectionIdRouteImport
      parentRoute: typeof OrgOrganizationSlugRoute
    }
    '/org/$organizationSlug/groups/': {
      id: '/org/$organizationSlug/groups/'
      path: '/groups'
      fullPath: '/org/$organizationSlug/groups/'
      preLoaderRoute: typeof OrgOrganizationSlugGroupsIndexRouteImport
      parentRoute: typeof OrgOrganizationSlugRoute
    }
    '/org/$organizationSlug/groups/$groupId': {
      id: '/org/$organizationSlug/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/org/$organizationSlug/groups/$groupId'
      preLoaderRoute: typeof OrgOrganizationSlugGroupsGroupIdRouteImport
      parentRoute: typeof OrgOrganizationSlugRoute
    }
    '/org/$organizationSlug/apps/$appId_/open': {
      id: '/org/$organizationSlug/apps/$appId_/open'
      path: '/apps/$appId/open'
      fullPath: '/org/$organizationSlug/apps/$appId/open'
      preLoaderRoute: typeof OrgOrganizationSlugAppsAppIdOpenRouteImport
      parentRoute: typeof OrgOrganizationSlugRoute
    }
    '/org/$organizationSlug/apps/$appId_/setup': {
      id: '/org/$organizationSlug/apps/$appId_/setup'
      path: '/apps/$appId/setup'
      fullPath: '/org/$organizationSlug/apps/$appId/setup'
      preLoaderRoute: typeof OrgOrganizationSlugAppsAppIdSetupRouteImport
      parentRoute: typeof OrgOrganizationSlugRoute
    }
    '/org/$organizationSlug/apps/add/': {
      id: '/org/$organizationSlug/apps/add/'
      path: '/apps/add'
      fullPath: '/org/$organizationSlug/apps/add/'
      preLoaderRoute: typeof OrgOrganizationSlugAppsAddIndexRouteImport
      parentRoute: typeof OrgOrganizationSlugRoute
    }
    '/org/$organizationSlug/apps/add/custom': {
      id: '/org/$organizationSlug/apps/add/custom'
      path: '/apps/add/custom'
      fullPath: '/org/$organizationSlug/apps/add/custom'
      preLoaderRoute: typeof OrgOrganizationSlugAppsAddCustomRouteImport
      parentRoute: typeof OrgOrganizationSlugRoute
    }
    '/org/$organizationSlug/webhooks/$appId/$subscriptionId': {
      id: '/org/$organizationSlug/webhooks/$appId/$subscriptionId'
      path: '/webhooks/$appId/$subscriptionId'
      fullPath: '/org/$organizationSlug/webhooks/$appId/$subscriptionId'
      preLoaderRoute: typeof OrgOrganizationSlugWebhooksAppIdSubscriptionIdRouteImport
      parentRoute: typeof OrgOrganizationSlugRoute
    }
  }
}

interface AccountRouteChildren {
  AccountProfileRoute: typeof AccountProfileRoute
  AccountSecurityRoute: typeof AccountSecurityRoute
  AccountTokensRoute: typeof AccountTokensRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountProfileRoute: AccountProfileRoute,
  AccountSecurityRoute: AccountSecurityRoute,
  AccountTokensRoute: AccountTokensRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface OrgOrganizationSlugRouteChildren {
  OrgOrganizationSlugApiKeysRoute: typeof OrgOrganizationSlugApiKeysRoute
  OrgOrganizationSlugBillingRoute: typeof OrgOrganizationSlugBillingRoute
  OrgOrganizationSlugConnectRoute: typeof OrgOrganizationSlugConnectRoute
  OrgOrganizationSlugOrganizationRoute: typeof OrgOrganizationSlugOrganizationRoute
  OrgOrganizationSlugIndexRoute: typeof OrgOrganizationSlugIndexRoute
  OrgOrganizationSlugApprovalsRunIdRoute: typeof OrgOrganizationSlugApprovalsRunIdRoute
  OrgOrganizationSlugAppsAppIdRoute: typeof OrgOrganizationSlugAppsAppIdRoute
  OrgOrganizationSlugConnectionsConnectionIdRoute: typeof OrgOrganizationSlugConnectionsConnectionIdRoute
  OrgOrganizationSlugGroupsGroupIdRoute: typeof OrgOrganizationSlugGroupsGroupIdRoute
  OrgOrganizationSlugAccountsIndexRoute: typeof OrgOrganizationSlugAccountsIndexRoute
  OrgOrganizationSlugApprovalsIndexRoute: typeof OrgOrganizationSlugApprovalsIndexRoute
  OrgOrganizationSlugAppsIndexRoute: typeof OrgOrganizationSlugAppsIndexRoute
  OrgOrganizationSlugGroupsIndexRoute: typeof OrgOrganizationSlugGroupsIndexRoute
  OrgOrganizationSlugAppsAppIdOpenRoute: typeof OrgOrganizationSlugAppsAppIdOpenRoute
  OrgOrganizationSlugAppsAppIdSetupRoute: typeof OrgOrganizationSlugAppsAppIdSetupRoute
  OrgOrganizationSlugAppsAddCustomRoute: typeof OrgOrganizationSlugAppsAddCustomRoute
  OrgOrganizationSlugWebhooksAppIdSubscriptionIdRoute: typeof OrgOrganizationSlugWebhooksAppIdSubscriptionIdRoute
  OrgOrganizationSlugAppsAddIndexRoute: typeof OrgOrganizationSlugAppsAddIndexRoute
}

const OrgOrganizationSlugRouteChildren: OrgOrganizationSlugRouteChildren = {
  OrgOrganizationSlugApiKeysRoute: OrgOrganizationSlugApiKeysRoute,
  OrgOrganizationSlugBillingRoute: OrgOrganizationSlugBillingRoute,
  OrgOrganizationSlugConnectRoute: OrgOrganizationSlugConnectRoute,
  OrgOrganizationSlugOrganizationRoute: OrgOrganizationSlugOrganizationRoute,
  OrgOrganizationSlugIndexRoute: OrgOrganizationSlugIndexRoute,
  OrgOrganizationSlugApprovalsRunIdRoute:
    OrgOrganizationSlugApprovalsRunIdRoute,
  OrgOrganizationSlugAppsAppIdRoute: OrgOrganizationSlugAppsAppIdRoute,
  OrgOrganizationSlugConnectionsConnectionIdRoute:
    OrgOrganizationSlugConnectionsConnectionIdRoute,
  OrgOrganizationSlugGroupsGroupIdRoute: OrgOrganizationSlugGroupsGroupIdRoute,
  OrgOrganizationSlugAccountsIndexRoute: OrgOrganizationSlugAccountsIndexRoute,
  OrgOrganizationSlugApprovalsIndexRoute:
    OrgOrganizationSlugApprovalsIndexRoute,
  OrgOrganizationSlugAppsIndexRoute: OrgOrganizationSlugAppsIndexRoute,
  OrgOrganizationSlugGroupsIndexRoute: OrgOrganizationSlugGroupsIndexRoute,
  OrgOrganizationSlugAppsAppIdOpenRoute: OrgOrganizationSlugAppsAppIdOpenRoute,
  OrgOrganizationSlugAppsAppIdSetupRoute:
    OrgOrganizationSlugAppsAppIdSetupRoute,
  OrgOrganizationSlugAppsAddCustomRoute: OrgOrganizationSlugAppsAddCustomRoute,
  OrgOrganizationSlugWebhooksAppIdSubscriptionIdRoute:
    OrgOrganizationSlugWebhooksAppIdSubscriptionIdRoute,
  OrgOrganizationSlugAppsAddIndexRoute: OrgOrganizationSlugAppsAddIndexRoute,
}

const OrgOrganizationSlugRouteWithChildren =
  OrgOrganizationSlugRoute._addFileChildren(OrgOrganizationSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  AppAuthRoute: AppAuthRoute,
  CreateRoute: CreateRoute,
  DeviceRoute: DeviceRoute,
  InviteRoute: InviteRoute,
  LoginRoute: LoginRoute,
  CreateAgentRoute: CreateAgentRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  LoginSsoRoute: LoginSsoRoute,
  McpAuthorizeRoute: McpAuthorizeRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  OrgOrganizationSlugRoute: OrgOrganizationSlugRouteWithChildren,
  McpApproveRequestIdRoute: McpApproveRequestIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
