/** Generate the ordinary local management app from the same OpenAPI document served to clients. */
import { packageFile } from "@executor-js/app-templates";
import { SourceFiles } from "@executor-js/sdk/core";
import { Effect } from "effect";
import { localManagementDocument } from "../contracts/management.ts";

/** Source contains no credentials or configured port; the selected account supplies them at invocation. */
export const executorAppSource = () =>
  Effect.sync(() => {
    const document = localManagementDocument();
    // The document is ours: credential placement is declared here rather than inferred from it.
    const configuration = {
      source: { document },
      allowedOrigin: "http://localhost",
      securitySchemes: document.components.securitySchemes,
      methods: { apiKey: [{ scheme: "apiKey", field: "token", part: "value", prefix: "" }] },
      oauth: [],
      baseUrl: "http://localhost",
    };
    return SourceFiles.make([
      {
        path: "index.ts",
        content: `import { defineApp, dynamicSkills } from "apps";
import { liveOpenapiRouter } from "apps/openapi";
import { wellKnownSkills } from "apps/skills";
import { executor } from "./provider.ts";
import configuration from "./openapi.json";

export default defineApp({ accounts: { executor } }, async (context) => {
  const baseUrl = context.accounts.executor.fields.baseUrl;
  const tools = liveOpenapiRouter({
    ...configuration,
    baseUrl,
    allowedOrigin: new URL(baseUrl).origin,
    cache: context.cache,
    account: {
      method: context.accounts.executor.method,
      fields: { token: context.accounts.executor.fields.apiKey },
    },
    fetch: context.fetch,
    ...(context.signal === undefined ? {} : { signal: context.signal }),
  });
  const skills = dynamicSkills({ list: () => wellKnownSkills({ url: baseUrl + "/.well-known/agent-skills/index.json", cache: context.cache, fetch: context.fetch, signal: context.signal }) });
  return { tools, dynamicSkills: skills };
});
`,
      },
      {
        path: "provider.ts",
        // Keep the existing provider definition and account slot so installs retain their connection.
        content: `import { defineProvider, object, secrets, string } from "apps";

export const executor = defineProvider({
  name: "Executor",
  auth: {
    apiKey: secrets({ label: "API key", fields: object({ baseUrl: string(), apiKey: string() }) }),
  },
});
`,
      },
      {
        path: "openapi.json",
        // The local API document requires authentication. Retain the credential-free
        // document generated by this installed server instead of fetching it anonymously.
        content: JSON.stringify(configuration, null, 2),
      },
      packageFile("executor"),
    ]);
  });
