/**
 * The dashboard tool-run review answer of the release built from main at cb81bce6b, frozen. Its
 * server encodes the answer with this schema and its dashboard decodes it with the same schema, so
 * the file checks both directions of a deploy or rollback across that release: a dashboard still
 * open from it reading a newer server's answer, and a newer dashboard reading its server's answer.
 *
 * Do not edit this file. Snapshot a later release in a new file named for its commit. Copied with
 * effect 4.0.1 (bun.lock at cb81bce6b) from these sources, by `git rev-parse cb81bce6b:<path>`:
 * - 323370d9fe7d9744565b48be51580c89a6bebd8b packages/sdk/src/contracts/tools.ts
 * - 84f42f96a694d3449b78d6e3c0291d10b588de17 packages/sdk/src/contracts/shared.ts
 * - 6ef0f2611a8b4d44ab7afd54940b431b4eb14b24 packages/sdk/src/implementation/tools.ts
 * - d323b70ccb529bcd9d487a09dbe912bb4bad986e packages/mcp/src/contracts/browser.ts
 * - 03ecce95dc685c6d5e9e9a80b5252e8613935429 packages/ui/src/contracts/browser-approval.ts
 * - 527d48ad7076358db7eff61629938cd7e545a72c packages/ui/src/implementation/dashboard/browser-approval.tsx
 * - 6aa79a79dfb46a12c46e4cf5512bb94f9bdb3553 packages/ui/src/implementation/dashboard/tool-runner.tsx
 * The schemas run with this repository's effect, not 4.0.1, once it is upgraded.
 */
import { Effect, Match, Schema } from "effect";

/** `ApprovalRequestId` in packages/sdk/src/contracts/shared.ts. */
const ApprovalRequestId = Schema.String.pipe(
  Schema.check(Schema.isPattern(/^apr_[\s\S]+$/u)),
  Schema.brand("apr"),
);
/** `ToolResumeResult` in packages/sdk/src/contracts/tools.ts. */
const ToolResumeResult = Schema.Union([
  Schema.Struct({
    status: Schema.Literal("completed"),
    value: Schema.Json,
    toolError: Schema.optionalKey(Schema.Literal(true)),
  }),
  Schema.Struct({ status: Schema.Literal("denied"), requestId: ApprovalRequestId }),
  Schema.Struct({ status: Schema.Literal("cancelled"), requestId: ApprovalRequestId }),
  Schema.Struct({
    status: Schema.Literal("failed"),
    requestId: ApprovalRequestId,
    reason: Schema.Literals(["expired", "context-changed", "execution-failed"]),
  }),
  Schema.Struct({ status: Schema.Literal("already-consumed"), requestId: ApprovalRequestId }),
]);
/** `BrowserToolRunAnswer` in packages/mcp/src/contracts/browser.ts. */
const ToolRunAnswer = Schema.Union([
  Schema.Struct({ status: Schema.Literal("answered"), result: ToolResumeResult }),
  Schema.Struct({ status: Schema.Literal("unavailable") }),
]);
type ToolRunAnswer = typeof ToolRunAnswer.Encoded;

/**
 * One answer for each member of that release's answer schema. Its server reports an approved call
 * that fails as `execution-failed` with no error (`resume` in packages/sdk/src/implementation/tools.ts).
 */
export const previousServerAnswers = (
  requestId: string,
): ReadonlyArray<readonly [label: string, answer: ToolRunAnswer]> => [
  [
    "execution-failed",
    { status: "answered", result: { status: "failed", requestId, reason: "execution-failed" } },
  ],
  ["completed", { status: "answered", result: { status: "completed", value: { ok: true } } }],
  [
    "completed with a tool error",
    { status: "answered", result: { status: "completed", value: "failed", toolError: true } },
  ],
  ["denied", { status: "answered", result: { status: "denied", requestId } }],
  ["cancelled", { status: "answered", result: { status: "cancelled", requestId } }],
  ["expired", { status: "answered", result: { status: "failed", requestId, reason: "expired" } }],
  [
    "context-changed",
    { status: "answered", result: { status: "failed", requestId, reason: "context-changed" } },
  ],
  ["already-consumed", { status: "answered", result: { status: "already-consumed", requestId } }],
  ["unavailable", { status: "unavailable" }],
];

/** `answered` in packages/ui/src/implementation/dashboard/tool-runner.tsx. */
const answered = (result: typeof ToolResumeResult.Type) =>
  Match.value(result).pipe(
    Match.discriminatorsExhaustive("status")({
      completed: ({ toolError }) =>
        toolError === true
          ? "Approved. The tool ran and reported an error, shown below."
          : "Approved. The tool ran, and its result is below.",
      denied: () => "Declined. Executor will not resume this saved call.",
      cancelled: () => "Cancelled. Executor will not resume this saved call.",
      failed: ({ reason }) =>
        Match.value(reason).pipe(
          Match.when(
            "context-changed",
            () =>
              "The app, profile or accounts changed since this call was saved, so Executor did not resume it. Run it again to review the current call.",
          ),
          Match.when(
            "execution-failed",
            () =>
              "The tool failed after you approved it. It may have already made changes. Check before running it again.",
          ),
          Match.when(
            "expired",
            () => "This request expired, so Executor will not resume this saved call.",
          ),
          Match.exhaustive,
        ),
      "already-consumed": () => "This request was already answered.",
    }),
  );

/**
 * What that release's dashboard shows after a 200 answer to a tool-run review: the answered
 * result's copy, nothing extra for `unavailable`, or its network failure when the body does not
 * decode (`request` in packages/ui/src/contracts/browser-approval.ts, `failureMessage` in
 * packages/ui/src/implementation/dashboard/browser-approval.tsx).
 */
export const previousToolRunCompletion = (body: unknown) =>
  Schema.decodeUnknownEffect(ToolRunAnswer)(body).pipe(
    Effect.map((answer) => (answer.status === "answered" ? answered(answer.result) : undefined)),
    Effect.catchTag("SchemaError", () => Effect.succeed("Cannot reach Executor. Try again.")),
  );
/** Whether that release's server can send `answer`, as a check on the answers above. */
export const isPreviousServerAnswer = Schema.is(ToolRunAnswer);
