/**
 * Compile host-owned browser scripts to string constants. Hosts inline or serve these strings, so
 * they must not come from Function.prototype.toString: a host bundle (minify, keepNames) rewrites
 * function bodies with helpers that do not exist in the page. Pass --check to fail when stale.
 */
import { build } from "esbuild";
import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("../", import.meta.url));
const output = join(root, "src/implementation/browser-scripts.gen.ts");
const scripts = {
  appWatchSource: "src/browser/app-watch.ts",
  appFailureSource: "src/browser/app-failure.ts",
  accountNoticeSource: "src/browser/account-notice.ts",
};

const compile = async (entry) => {
  const result = await build({
    entryPoints: [join(root, entry)],
    bundle: true,
    write: false,
    format: "iife",
    platform: "browser",
    target: "es2022",
    minify: true,
    legalComments: "none",
  });
  const [file] = result.outputFiles;
  if (file === undefined) throw new Error(`No output for ${entry}`);
  // Hosts inline these in <script> elements.
  if (/<\/script/i.test(file.text)) throw new Error(`${entry} must not contain </script`);
  return file.text.trim();
};

const constants = await Promise.all(
  Object.entries(scripts).map(
    async ([name, entry]) =>
      `/** Compiled from ${entry}. */\nexport const ${name} = ${JSON.stringify(await compile(entry))};\n`,
  ),
);
const generated = `// Generated by packages/apps/scripts/browser-scripts.mjs. Do not edit.\n\n${constants.join("\n")}`;

if (process.argv.includes("--check")) {
  const current = await readFile(output, "utf8").catch(() => "");
  if (current !== generated) {
    console.error("browser-scripts.gen.ts is stale. Run: bun run apps:browser-scripts");
    process.exit(1);
  }
} else {
  await writeFile(output, generated);
}
