/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as AppAuthRouteImport } from './routes/app-auth'
import { Route as DashboardInventoryRouteImport } from './routes/_dashboard._inventory'
import { Route as DashboardConnectRouteImport } from './routes/_dashboard.connect'
import { Route as AccountConnectConnectionIdRouteImport } from './routes/account-connect.$connectionId'
import { Route as McpAuthorizeRouteImport } from './routes/mcp.authorize'
import { Route as DashboardInventoryIndexRouteImport } from './routes/_dashboard._inventory.index'
import { Route as DashboardInventorySplatRouteImport } from './routes/_dashboard._inventory.$'
import { Route as DashboardApprovalsIndexRouteImport } from './routes/_dashboard.approvals.index'
import { Route as DashboardApprovalsRunIdRouteImport } from './routes/_dashboard.approvals.$runId'
import { Route as McpApproveRequestIdRouteImport } from './routes/mcp.approve.$requestId'
import { Route as DashboardInventoryAccountsIndexRouteImport } from './routes/_dashboard._inventory.accounts.index'
import { Route as DashboardInventoryAccountsAddRouteImport } from './routes/_dashboard._inventory.accounts.add'
import { Route as DashboardInventoryAppsIndexRouteImport } from './routes/_dashboard._inventory.apps.index'
import { Route as DashboardInventoryAppsAppIdRouteImport } from './routes/_dashboard._inventory.apps.$appId'
import { Route as DashboardInventoryAppsAddRouteImport } from './routes/_dashboard._inventory.apps.add'
import { Route as DashboardWebhooksAppIdSubscriptionIdRouteImport } from './routes/_dashboard.webhooks.$appId.$subscriptionId'
import { Route as DashboardInventoryAccountsAccountIdCredentialsRouteImport } from './routes/_dashboard._inventory.accounts.$accountId_.credentials'
import { Route as DashboardInventoryApiOauthCallbackRouteImport } from './routes/_dashboard._inventory.api.oauth.callback'
import { Route as DashboardInventoryAppsAppIdDeleteRouteImport } from './routes/_dashboard._inventory.apps.$appId_.delete'
import { Route as DashboardInventoryAppsAppIdOpenRouteImport } from './routes/_dashboard._inventory.apps.$appId_.open'
import { Route as DashboardInventoryAppsAppIdSetupRouteImport } from './routes/_dashboard._inventory.apps.$appId_.setup'
import { Route as DashboardInventoryAppsAddCustomRouteImport } from './routes/_dashboard._inventory.apps.add_.custom'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthRoute = AppAuthRouteImport.update({
  id: '/app-auth',
  path: '/app-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardInventoryRoute = DashboardInventoryRouteImport.update({
  id: '/_inventory',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConnectRoute = DashboardConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => DashboardRoute,
} as any)
const AccountConnectConnectionIdRoute =
  AccountConnectConnectionIdRouteImport.update({
    id: '/account-connect/$connectionId',
    path: '/account-connect/$connectionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const McpAuthorizeRoute = McpAuthorizeRouteImport.update({
  id: '/mcp/authorize',
  path: '/mcp/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardInventoryIndexRoute = DashboardInventoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardInventoryRoute,
} as any)
const DashboardInventorySplatRoute = DashboardInventorySplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DashboardInventoryRoute,
} as any)
const DashboardApprovalsIndexRoute = DashboardApprovalsIndexRouteImport.update({
  id: '/approvals/',
  path: '/approvals/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApprovalsRunIdRoute = DashboardApprovalsRunIdRouteImport.update({
  id: '/approvals/$runId',
  path: '/approvals/$runId',
  getParentRoute: () => DashboardRoute,
} as any)
const McpApproveRequestIdRoute = McpApproveRequestIdRouteImport.update({
  id: '/mcp/approve/$requestId',
  path: '/mcp/approve/$requestId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardInventoryAccountsIndexRoute =
  DashboardInventoryAccountsIndexRouteImport.update({
    id: '/accounts/',
    path: '/accounts/',
    getParentRoute: () => DashboardInventoryRoute,
  } as any)
const DashboardInventoryAccountsAddRoute =
  DashboardInventoryAccountsAddRouteImport.update({
    id: '/accounts/add',
    path: '/accounts/add',
    getParentRoute: () => DashboardInventoryRoute,
  } as any)
const DashboardInventoryAppsIndexRoute =
  DashboardInventoryAppsIndexRouteImport.update({
    id: '/apps/',
    path: '/apps/',
    getParentRoute: () => DashboardInventoryRoute,
  } as any)
const DashboardInventoryAppsAppIdRoute =
  DashboardInventoryAppsAppIdRouteImport.update({
    id: '/apps/$appId',
    path: '/apps/$appId',
    getParentRoute: () => DashboardInventoryRoute,
  } as any)
const DashboardInventoryAppsAddRoute =
  DashboardInventoryAppsAddRouteImport.update({
    id: '/apps/add',
    path: '/apps/add',
    getParentRoute: () => DashboardInventoryRoute,
  } as any)
const DashboardWebhooksAppIdSubscriptionIdRoute =
  DashboardWebhooksAppIdSubscriptionIdRouteImport.update({
    id: '/webhooks/$appId/$subscriptionId',
    path: '/webhooks/$appId/$subscriptionId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardInventoryAccountsAccountIdCredentialsRoute =
  DashboardInventoryAccountsAccountIdCredentialsRouteImport.update({
    id: '/accounts/$accountId_/credentials',
    path: '/accounts/$accountId/credentials',
    getParentRoute: () => DashboardInventoryRoute,
  } as any)
const DashboardInventoryApiOauthCallbackRoute =
  DashboardInventoryApiOauthCallbackRouteImport.update({
    id: '/api/oauth/callback',
    path: '/api/oauth/callback',
    getParentRoute: () => DashboardInventoryRoute,
  } as any)
const DashboardInventoryAppsAppIdDeleteRoute =
  DashboardInventoryAppsAppIdDeleteRouteImport.update({
    id: '/apps/$appId_/delete',
    path: '/apps/$appId/delete',
    getParentRoute: () => DashboardInventoryRoute,
  } as any)
const DashboardInventoryAppsAppIdOpenRoute =
  DashboardInventoryAppsAppIdOpenRouteImport.update({
    id: '/apps/$appId_/open',
    path: '/apps/$appId/open',
    getParentRoute: () => DashboardInventoryRoute,
  } as any)
const DashboardInventoryAppsAppIdSetupRoute =
  DashboardInventoryAppsAppIdSetupRouteImport.update({
    id: '/apps/$appId_/setup',
    path: '/apps/$appId/setup',
    getParentRoute: () => DashboardInventoryRoute,
  } as any)
const DashboardInventoryAppsAddCustomRoute =
  DashboardInventoryAppsAddCustomRouteImport.update({
    id: '/apps/add_/custom',
    path: '/apps/add/custom',
    getParentRoute: () => DashboardInventoryRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardInventoryIndexRoute
  '/app-auth': typeof AppAuthRoute
  '/connect': typeof DashboardConnectRoute
  '/account-connect/$connectionId': typeof AccountConnectConnectionIdRoute
  '/mcp/authorize': typeof McpAuthorizeRoute
  '/$': typeof DashboardInventorySplatRoute
  '/approvals/$runId': typeof DashboardApprovalsRunIdRoute
  '/mcp/approve/$requestId': typeof McpApproveRequestIdRoute
  '/approvals/': typeof DashboardApprovalsIndexRoute
  '/accounts/add': typeof DashboardInventoryAccountsAddRoute
  '/apps/$appId': typeof DashboardInventoryAppsAppIdRoute
  '/apps/add': typeof DashboardInventoryAppsAddRoute
  '/webhooks/$appId/$subscriptionId': typeof DashboardWebhooksAppIdSubscriptionIdRoute
  '/accounts/': typeof DashboardInventoryAccountsIndexRoute
  '/apps/': typeof DashboardInventoryAppsIndexRoute
  '/accounts/$accountId/credentials': typeof DashboardInventoryAccountsAccountIdCredentialsRoute
  '/api/oauth/callback': typeof DashboardInventoryApiOauthCallbackRoute
  '/apps/$appId/delete': typeof DashboardInventoryAppsAppIdDeleteRoute
  '/apps/$appId/open': typeof DashboardInventoryAppsAppIdOpenRoute
  '/apps/$appId/setup': typeof DashboardInventoryAppsAppIdSetupRoute
  '/apps/add/custom': typeof DashboardInventoryAppsAddCustomRoute
}
export interface FileRoutesByTo {
  '/': typeof DashboardInventoryIndexRoute
  '/app-auth': typeof AppAuthRoute
  '/connect': typeof DashboardConnectRoute
  '/account-connect/$connectionId': typeof AccountConnectConnectionIdRoute
  '/mcp/authorize': typeof McpAuthorizeRoute
  '/$': typeof DashboardInventorySplatRoute
  '/approvals/$runId': typeof DashboardApprovalsRunIdRoute
  '/mcp/approve/$requestId': typeof McpApproveRequestIdRoute
  '/approvals': typeof DashboardApprovalsIndexRoute
  '/accounts/add': typeof DashboardInventoryAccountsAddRoute
  '/apps/$appId': typeof DashboardInventoryAppsAppIdRoute
  '/apps/add': typeof DashboardInventoryAppsAddRoute
  '/webhooks/$appId/$subscriptionId': typeof DashboardWebhooksAppIdSubscriptionIdRoute
  '/accounts': typeof DashboardInventoryAccountsIndexRoute
  '/apps': typeof DashboardInventoryAppsIndexRoute
  '/accounts/$accountId/credentials': typeof DashboardInventoryAccountsAccountIdCredentialsRoute
  '/api/oauth/callback': typeof DashboardInventoryApiOauthCallbackRoute
  '/apps/$appId/delete': typeof DashboardInventoryAppsAppIdDeleteRoute
  '/apps/$appId/open': typeof DashboardInventoryAppsAppIdOpenRoute
  '/apps/$appId/setup': typeof DashboardInventoryAppsAppIdSetupRoute
  '/apps/add/custom': typeof DashboardInventoryAppsAddCustomRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/app-auth': typeof AppAuthRoute
  '/_dashboard/_inventory': typeof DashboardInventoryRouteWithChildren
  '/_dashboard/connect': typeof DashboardConnectRoute
  '/account-connect/$connectionId': typeof AccountConnectConnectionIdRoute
  '/mcp/authorize': typeof McpAuthorizeRoute
  '/_dashboard/_inventory/$': typeof DashboardInventorySplatRoute
  '/_dashboard/approvals/$runId': typeof DashboardApprovalsRunIdRoute
  '/mcp/approve/$requestId': typeof McpApproveRequestIdRoute
  '/_dashboard/_inventory/': typeof DashboardInventoryIndexRoute
  '/_dashboard/approvals/': typeof DashboardApprovalsIndexRoute
  '/_dashboard/_inventory/accounts/add': typeof DashboardInventoryAccountsAddRoute
  '/_dashboard/_inventory/apps/$appId': typeof DashboardInventoryAppsAppIdRoute
  '/_dashboard/_inventory/apps/add': typeof DashboardInventoryAppsAddRoute
  '/_dashboard/webhooks/$appId/$subscriptionId': typeof DashboardWebhooksAppIdSubscriptionIdRoute
  '/_dashboard/_inventory/accounts/': typeof DashboardInventoryAccountsIndexRoute
  '/_dashboard/_inventory/apps/': typeof DashboardInventoryAppsIndexRoute
  '/_dashboard/_inventory/accounts/$accountId_/credentials': typeof DashboardInventoryAccountsAccountIdCredentialsRoute
  '/_dashboard/_inventory/api/oauth/callback': typeof DashboardInventoryApiOauthCallbackRoute
  '/_dashboard/_inventory/apps/$appId_/delete': typeof DashboardInventoryAppsAppIdDeleteRoute
  '/_dashboard/_inventory/apps/$appId_/open': typeof DashboardInventoryAppsAppIdOpenRoute
  '/_dashboard/_inventory/apps/$appId_/setup': typeof DashboardInventoryAppsAppIdSetupRoute
  '/_dashboard/_inventory/apps/add_/custom': typeof DashboardInventoryAppsAddCustomRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app-auth'
    | '/connect'
    | '/account-connect/$connectionId'
    | '/mcp/authorize'
    | '/$'
    | '/approvals/$runId'
    | '/mcp/approve/$requestId'
    | '/approvals/'
    | '/accounts/add'
    | '/apps/$appId'
    | '/apps/add'
    | '/webhooks/$appId/$subscriptionId'
    | '/accounts/'
    | '/apps/'
    | '/accounts/$accountId/credentials'
    | '/api/oauth/callback'
    | '/apps/$appId/delete'
    | '/apps/$appId/open'
    | '/apps/$appId/setup'
    | '/apps/add/custom'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app-auth'
    | '/connect'
    | '/account-connect/$connectionId'
    | '/mcp/authorize'
    | '/$'
    | '/approvals/$runId'
    | '/mcp/approve/$requestId'
    | '/approvals'
    | '/accounts/add'
    | '/apps/$appId'
    | '/apps/add'
    | '/webhooks/$appId/$subscriptionId'
    | '/accounts'
    | '/apps'
    | '/accounts/$accountId/credentials'
    | '/api/oauth/callback'
    | '/apps/$appId/delete'
    | '/apps/$appId/open'
    | '/apps/$appId/setup'
    | '/apps/add/custom'
  id:
    | '__root__'
    | '/_dashboard'
    | '/app-auth'
    | '/_dashboard/_inventory'
    | '/_dashboard/connect'
    | '/account-connect/$connectionId'
    | '/mcp/authorize'
    | '/_dashboard/_inventory/$'
    | '/_dashboard/approvals/$runId'
    | '/mcp/approve/$requestId'
    | '/_dashboard/_inventory/'
    | '/_dashboard/approvals/'
    | '/_dashboard/_inventory/accounts/add'
    | '/_dashboard/_inventory/apps/$appId'
    | '/_dashboard/_inventory/apps/add'
    | '/_dashboard/webhooks/$appId/$subscriptionId'
    | '/_dashboard/_inventory/accounts/'
    | '/_dashboard/_inventory/apps/'
    | '/_dashboard/_inventory/accounts/$accountId_/credentials'
    | '/_dashboard/_inventory/api/oauth/callback'
    | '/_dashboard/_inventory/apps/$appId_/delete'
    | '/_dashboard/_inventory/apps/$appId_/open'
    | '/_dashboard/_inventory/apps/$appId_/setup'
    | '/_dashboard/_inventory/apps/add_/custom'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  AppAuthRoute: typeof AppAuthRoute
  AccountConnectConnectionIdRoute: typeof AccountConnectConnectionIdRoute
  McpAuthorizeRoute: typeof McpAuthorizeRoute
  McpApproveRequestIdRoute: typeof McpApproveRequestIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-auth': {
      id: '/app-auth'
      path: '/app-auth'
      fullPath: '/app-auth'
      preLoaderRoute: typeof AppAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/_inventory': {
      id: '/_dashboard/_inventory'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardInventoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/connect': {
      id: '/_dashboard/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof DashboardConnectRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/account-connect/$connectionId': {
      id: '/account-connect/$connectionId'
      path: '/account-connect/$connectionId'
      fullPath: '/account-connect/$connectionId'
      preLoaderRoute: typeof AccountConnectConnectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp/authorize': {
      id: '/mcp/authorize'
      path: '/mcp/authorize'
      fullPath: '/mcp/authorize'
      preLoaderRoute: typeof McpAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/_inventory/': {
      id: '/_dashboard/_inventory/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardInventoryIndexRouteImport
      parentRoute: typeof DashboardInventoryRoute
    }
    '/_dashboard/_inventory/$': {
      id: '/_dashboard/_inventory/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof DashboardInventorySplatRouteImport
      parentRoute: typeof DashboardInventoryRoute
    }
    '/_dashboard/approvals/': {
      id: '/_dashboard/approvals/'
      path: '/approvals'
      fullPath: '/approvals/'
      preLoaderRoute: typeof DashboardApprovalsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/approvals/$runId': {
      id: '/_dashboard/approvals/$runId'
      path: '/approvals/$runId'
      fullPath: '/approvals/$runId'
      preLoaderRoute: typeof DashboardApprovalsRunIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/mcp/approve/$requestId': {
      id: '/mcp/approve/$requestId'
      path: '/mcp/approve/$requestId'
      fullPath: '/mcp/approve/$requestId'
      preLoaderRoute: typeof McpApproveRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/_inventory/accounts/': {
      id: '/_dashboard/_inventory/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof DashboardInventoryAccountsIndexRouteImport
      parentRoute: typeof DashboardInventoryRoute
    }
    '/_dashboard/_inventory/accounts/add': {
      id: '/_dashboard/_inventory/accounts/add'
      path: '/accounts/add'
      fullPath: '/accounts/add'
      preLoaderRoute: typeof DashboardInventoryAccountsAddRouteImport
      parentRoute: typeof DashboardInventoryRoute
    }
    '/_dashboard/_inventory/apps/': {
      id: '/_dashboard/_inventory/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof DashboardInventoryAppsIndexRouteImport
      parentRoute: typeof DashboardInventoryRoute
    }
    '/_dashboard/_inventory/apps/$appId': {
      id: '/_dashboard/_inventory/apps/$appId'
      path: '/apps/$appId'
      fullPath: '/apps/$appId'
      preLoaderRoute: typeof DashboardInventoryAppsAppIdRouteImport
      parentRoute: typeof DashboardInventoryRoute
    }
    '/_dashboard/_inventory/apps/add': {
      id: '/_dashboard/_inventory/apps/add'
      path: '/apps/add'
      fullPath: '/apps/add'
      preLoaderRoute: typeof DashboardInventoryAppsAddRouteImport
      parentRoute: typeof DashboardInventoryRoute
    }
    '/_dashboard/webhooks/$appId/$subscriptionId': {
      id: '/_dashboard/webhooks/$appId/$subscriptionId'
      path: '/webhooks/$appId/$subscriptionId'
      fullPath: '/webhooks/$appId/$subscriptionId'
      preLoaderRoute: typeof DashboardWebhooksAppIdSubscriptionIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/_inventory/accounts/$accountId_/credentials': {
      id: '/_dashboard/_inventory/accounts/$accountId_/credentials'
      path: '/accounts/$accountId/credentials'
      fullPath: '/accounts/$accountId/credentials'
      preLoaderRoute: typeof DashboardInventoryAccountsAccountIdCredentialsRouteImport
      parentRoute: typeof DashboardInventoryRoute
    }
    '/_dashboard/_inventory/api/oauth/callback': {
      id: '/_dashboard/_inventory/api/oauth/callback'
      path: '/api/oauth/callback'
      fullPath: '/api/oauth/callback'
      preLoaderRoute: typeof DashboardInventoryApiOauthCallbackRouteImport
      parentRoute: typeof DashboardInventoryRoute
    }
    '/_dashboard/_inventory/apps/$appId_/delete': {
      id: '/_dashboard/_inventory/apps/$appId_/delete'
      path: '/apps/$appId/delete'
      fullPath: '/apps/$appId/delete'
      preLoaderRoute: typeof DashboardInventoryAppsAppIdDeleteRouteImport
      parentRoute: typeof DashboardInventoryRoute
    }
    '/_dashboard/_inventory/apps/$appId_/open': {
      id: '/_dashboard/_inventory/apps/$appId_/open'
      path: '/apps/$appId/open'
      fullPath: '/apps/$appId/open'
      preLoaderRoute: typeof DashboardInventoryAppsAppIdOpenRouteImport
      parentRoute: typeof DashboardInventoryRoute
    }
    '/_dashboard/_inventory/apps/$appId_/setup': {
      id: '/_dashboard/_inventory/apps/$appId_/setup'
      path: '/apps/$appId/setup'
      fullPath: '/apps/$appId/setup'
      preLoaderRoute: typeof DashboardInventoryAppsAppIdSetupRouteImport
      parentRoute: typeof DashboardInventoryRoute
    }
    '/_dashboard/_inventory/apps/add_/custom': {
      id: '/_dashboard/_inventory/apps/add_/custom'
      path: '/apps/add/custom'
      fullPath: '/apps/add/custom'
      preLoaderRoute: typeof DashboardInventoryAppsAddCustomRouteImport
      parentRoute: typeof DashboardInventoryRoute
    }
  }
}

interface DashboardInventoryRouteChildren {
  DashboardInventorySplatRoute: typeof DashboardInventorySplatRoute
  DashboardInventoryIndexRoute: typeof DashboardInventoryIndexRoute
  DashboardInventoryAccountsAddRoute: typeof DashboardInventoryAccountsAddRoute
  DashboardInventoryAppsAppIdRoute: typeof DashboardInventoryAppsAppIdRoute
  DashboardInventoryAppsAddRoute: typeof DashboardInventoryAppsAddRoute
  DashboardInventoryAccountsIndexRoute: typeof DashboardInventoryAccountsIndexRoute
  DashboardInventoryAppsIndexRoute: typeof DashboardInventoryAppsIndexRoute
  DashboardInventoryAccountsAccountIdCredentialsRoute: typeof DashboardInventoryAccountsAccountIdCredentialsRoute
  DashboardInventoryApiOauthCallbackRoute: typeof DashboardInventoryApiOauthCallbackRoute
  DashboardInventoryAppsAppIdDeleteRoute: typeof DashboardInventoryAppsAppIdDeleteRoute
  DashboardInventoryAppsAppIdOpenRoute: typeof DashboardInventoryAppsAppIdOpenRoute
  DashboardInventoryAppsAppIdSetupRoute: typeof DashboardInventoryAppsAppIdSetupRoute
  DashboardInventoryAppsAddCustomRoute: typeof DashboardInventoryAppsAddCustomRoute
}

const DashboardInventoryRouteChildren: DashboardInventoryRouteChildren = {
  DashboardInventorySplatRoute: DashboardInventorySplatRoute,
  DashboardInventoryIndexRoute: DashboardInventoryIndexRoute,
  DashboardInventoryAccountsAddRoute: DashboardInventoryAccountsAddRoute,
  DashboardInventoryAppsAppIdRoute: DashboardInventoryAppsAppIdRoute,
  DashboardInventoryAppsAddRoute: DashboardInventoryAppsAddRoute,
  DashboardInventoryAccountsIndexRoute: DashboardInventoryAccountsIndexRoute,
  DashboardInventoryAppsIndexRoute: DashboardInventoryAppsIndexRoute,
  DashboardInventoryAccountsAccountIdCredentialsRoute:
    DashboardInventoryAccountsAccountIdCredentialsRoute,
  DashboardInventoryApiOauthCallbackRoute:
    DashboardInventoryApiOauthCallbackRoute,
  DashboardInventoryAppsAppIdDeleteRoute:
    DashboardInventoryAppsAppIdDeleteRoute,
  DashboardInventoryAppsAppIdOpenRoute: DashboardInventoryAppsAppIdOpenRoute,
  DashboardInventoryAppsAppIdSetupRoute: DashboardInventoryAppsAppIdSetupRoute,
  DashboardInventoryAppsAddCustomRoute: DashboardInventoryAppsAddCustomRoute,
}

const DashboardInventoryRouteWithChildren =
  DashboardInventoryRoute._addFileChildren(DashboardInventoryRouteChildren)

interface DashboardRouteChildren {
  DashboardInventoryRoute: typeof DashboardInventoryRouteWithChildren
  DashboardConnectRoute: typeof DashboardConnectRoute
  DashboardApprovalsRunIdRoute: typeof DashboardApprovalsRunIdRoute
  DashboardApprovalsIndexRoute: typeof DashboardApprovalsIndexRoute
  DashboardWebhooksAppIdSubscriptionIdRoute: typeof DashboardWebhooksAppIdSubscriptionIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardInventoryRoute: DashboardInventoryRouteWithChildren,
  DashboardConnectRoute: DashboardConnectRoute,
  DashboardApprovalsRunIdRoute: DashboardApprovalsRunIdRoute,
  DashboardApprovalsIndexRoute: DashboardApprovalsIndexRoute,
  DashboardWebhooksAppIdSubscriptionIdRoute:
    DashboardWebhooksAppIdSubscriptionIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  AppAuthRoute: AppAuthRoute,
  AccountConnectConnectionIdRoute: AccountConnectConnectionIdRoute,
  McpAuthorizeRoute: McpAuthorizeRoute,
  McpApproveRequestIdRoute: McpApproveRequestIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
