/** Shared authorization vocabulary and pure decisions for Executor products. */
export {
  Action,
  ToolScope,
  EventScope,
  RunTarget,
  AppPermission,
  ToolSelection,
  AuthorizationPolicy,
  type ToolIdentity,
  type ToolRequest,
  fullAuthority,
  noAuthority,
  selectedAuthority,
  permitsAction,
  permitsApp,
  eventAccess,
  permitsEvent,
  permitsTool,
  permitsTarget,
  permitsRouter,
  selectsApp,
  selectsTool,
  selectsTarget,
  requiresToolMetadata,
  isToolSelectionSubset,
  permittedAppIds,
} from "./contracts/policy.ts";
