/** Shared grant contracts and enforcement for product hosts. */
export {
  GrantId,
  ApprovalMode,
  ConnectionId,
  McpAddress,
  GrantTarget,
  requestedMcpAddress,
  mcpResource,
  mcpOAuthResources,
  type OriginList,
  type ResourceOrigins,
  singleResourceOrigin,
  requestResourceOrigin,
  grantTarget,
  mcpResourceMetadataUrl,
  GrantPolicy,
  grantAuthorization,
  grantEventAccess,
  Grant,
  AppPermission,
  GrantForbidden,
  GrantRefusal,
  deliveryRefusal,
  permitsBrowserApproval,
} from "./contracts/grant.ts";
export { restrictMcpBackend } from "./implementation/backend.ts";
