/**
 * Host protocol 1: the messages that cross between a host and a retained app bundle.
 *
 * This protocol is released and frozen. Retained builds and published `apps` versions speak it,
 * and every later host must keep running and rebuilding them unchanged. `bun run check` compares
 * `protocol1` with `packages/apps/protocols/1.json` and fails on any difference, including changes
 * to the schemas it imports. Do not edit this file or the schemas it reaches to change the wire
 * format. Define the next protocol instead and give the host an adapter for this one. If a
 * referenced schema must change for other reasons, first copy its current definition here.
 * See notes/apps-publishing.md.
 */
import { Schema } from "effect";
import { CacheCommand, CacheReply } from "@executor-js/app-cache/contracts";
import { DatabaseSchema } from "@executor-js/app-data/contracts";
import { OpenapiResponseError } from "../api-response-error.ts";
import {
  ApprovalElicitation,
  ElicitationFailed,
  ElicitationReply,
  FormElicitation,
} from "../elicitation.ts";
import { OAuth2Config } from "./oauth.ts";
import { OperationSchedule } from "../schedules.ts";
import { AccountId, JsonObject, JsonValue } from "../schema.ts";
import { AppSkills, SkillLoadFailed } from "../skills.ts";
import { ToolAnnotations } from "../tools.ts";
import { WebhookCommand } from "../webhook-protocol.ts";
import {
  WorkflowCommand,
  WorkflowControlCommand,
  WorkflowReplay,
  WorkflowRpcCommand,
  WorkflowRunId,
} from "../workflows.ts";

/** Protocol 1's provider failure, as released: a reason, an HTTP status and the account used. */
export class ProviderError extends Schema.TaggedError<ProviderError>()("ProviderError", {
  reason: Schema.Literals(["unauthorized", "forbidden", "rate_limited", "unavailable", "rejected"]),
  status: Schema.optional(Schema.Int.check(Schema.isBetween({ minimum: 100, maximum: 599 }))),
  accountId: Schema.optional(AccountId),
}) {}

/** Protocol 1's MCP failure, as released: a phase, a reason and an HTTP status. */
export class McpError extends Schema.TaggedError<McpError>()("McpError", {
  phase: Schema.Literals(["connect", "discover", "call", "schema", "transport"]),
  reason: Schema.Literals([
    "request",
    "unauthorized",
    "invalid_response",
    "timeout",
    "invalid_input",
  ]),
  status: Schema.optional(Schema.Number),
}) {}

/** Protocol 1's workflow failure: a reason code only, as released. */
export class WorkflowFailure extends Schema.TaggedError<WorkflowFailure>()("WorkflowFailure", {
  reason: Schema.Literals([
    "unavailable",
    "not_found",
    "input",
    "output",
    "operation",
    "approval",
    "credentials",
    "terminated",
    "execution",
    "conflict",
    "engine",
  ]),
  retryable: Schema.Boolean,
}) {}
/** Protocol 1's workflow step reply, carrying its own failure. */
export const WorkflowRpcResult = Schema.Union([
  Schema.Struct({ ok: Schema.Literal(true), value: JsonValue }),
  Schema.Struct({ ok: Schema.Literal(false), error: WorkflowFailure }),
]);

/** Serializable auth methods shared with SDK hosts; protocol configuration has one schema. */
export const DeclaredAuthMethod = Schema.Union([
  Schema.Struct({ type: Schema.Literal("secrets"), label: Schema.String, fields: JsonObject }),
  Schema.Struct({
    type: Schema.Literal("oauth2"),
    ...OAuth2Config.members[0].fields,
    response: JsonObject,
  }),
  Schema.Struct({
    type: Schema.Literal("oauth2"),
    ...OAuth2Config.members[1].fields,
    response: JsonObject,
  }),
  Schema.Struct({
    type: Schema.Literal("oauth2"),
    ...OAuth2Config.members[2].fields,
    response: JsonObject,
  }),
  Schema.Struct({
    type: Schema.Literal("oauth2"),
    ...OAuth2Config.members[3].fields,
    response: JsonObject,
  }),
]);

/** Serializable declaration of a provider's named authentication methods. */
export const DeclaredProvider = Schema.Struct({
  name: Schema.NonEmptyString,
  auth: Schema.Record(Schema.NonEmptyString, DeclaredAuthMethod),
});
/** Credential-free provider declaration; content matching remains host policy. */
export type DeclaredProvider = typeof DeclaredProvider.Type;

/** Account slots available without binding accounts or evaluating the app factory. */
export const DeclaredRequirements = Schema.Struct({
  /** Protocol support of this retained framework build, not an author-declared requirement. */
  capabilities: Schema.optionalKey(
    Schema.Struct({
      skills: Schema.Literal(true),
      /** Accepts inspect detail and tools. Earlier builds reject both as excess fields. */
      toolIndex: Schema.optionalKey(Schema.Literal(true)),
      /** Accepts skills sources and reports whether the catalog includes a live loader. */
      skillSources: Schema.optionalKey(Schema.Literal(true)),
      /** Accepts scheduled inspection. Earlier builds reject it as an excess field. */
      scheduledTools: Schema.optionalKey(Schema.Literal(true)),
    }),
  ),
  database: Schema.optionalKey(DatabaseSchema),
  accounts: Schema.Record(
    Schema.NonEmptyString,
    Schema.Struct({
      definition: DeclaredProvider,
      cardinality: Schema.Literals(["one", "many"]),
    }),
  ),
});
/** Parsed declared account requirements. */
export type DeclaredRequirements = typeof DeclaredRequirements.Type;

/** Host-resolved credentials for one stable saved account. Never a request DTO. */
export const ResolvedAccount = Schema.Struct({
  id: AccountId,
  provider: DeclaredProvider,
  method: Schema.NonEmptyString,
  /**
   * Changes when the account is reconnected or its credentials replaced, not on renewal. Hosts
   * send it since credential generations; `apps@0.0.1-beta.0` and `beta.1` ignore it.
   */
  generation: Schema.optionalKey(Schema.Int),
  fields: JsonObject,
});
/** Parsed host account binding. */
export type ResolvedAccount = typeof ResolvedAccount.Type;

/** Full saved selection resolved by the trusted caller; [] differs from a missing slot. */
export const ResolvedAccounts = Schema.Record(
  Schema.NonEmptyString,
  Schema.Union([ResolvedAccount, Schema.Array(ResolvedAccount)]),
);
/** Parsed host selections, kept redacted until native account binding. */
export type ResolvedAccounts = typeof ResolvedAccounts.Type;

/** Trusted approval for one decoded call. Never accepted in public command JSON. */
export const TrustedToolApproval = Schema.Struct({ tool: Schema.NonEmptyString, input: JsonValue });
export type TrustedToolApproval = typeof TrustedToolApproval.Type;

/** Absolute Unix time in milliseconds; remote hosts enforce it inside the operation transaction. */
export const InvocationDeadline = Schema.Finite.check(Schema.isGreaterThanOrEqualTo(0));

/** Serializable live tool metadata; executable callbacks never cross this boundary. */
export const HostedTool = Schema.Struct({
  schedules: Schema.optionalKey(Schema.Array(OperationSchedule)),
  name: Schema.NonEmptyString,
  description: Schema.String,
  inputSchema: JsonObject,
  readOnly: Schema.optionalKey(Schema.Boolean),
  title: Schema.optionalKey(Schema.String),
  outputSchema: Schema.optionalKey(JsonObject),
  annotations: Schema.optionalKey(ToolAnnotations),
  _meta: Schema.optionalKey(JsonObject),
});
/** Parsed live tool description. */
export type HostedTool = typeof HostedTool.Type;

/** Catalog entry without schemas. Browsing lists these and reads one full tool on selection. */
export const HostedToolSummary = HostedTool.mapFields(
  ({ inputSchema: _input, outputSchema: _output, _meta, ...fields }) => fields,
);
export type HostedToolSummary = typeof HostedToolSummary.Type;

/**
 * A skill catalog and whether any of it came from `dynamicSkills`. Without a live loader the
 * catalog is determined by the build and its evaluation inputs; with one it reflects a publisher.
 */
export const SkillSources = Schema.Struct({ skills: AppSkills, dynamic: Schema.Boolean });
export type SkillSources = typeof SkillSources.Type;
/** Either response shape; `dynamic` is unknown for builds that predate skillSources. */
export const SkillCatalogResponse = Schema.Union([SkillSources, AppSkills]);

/** Framework-owned dispatch, independent of app-authored HTTP routing. */
export const HostRequest = Schema.Union([
  WorkflowCommand,
  WebhookCommand,
  Schema.Struct({ operation: Schema.Literal("requirements") }),
  Schema.Struct({
    operation: Schema.Literal("inspect"),
    /** Omit schemas. Only builds that declare the toolIndex capability accept this. */
    detail: Schema.optionalKey(Schema.Literal("summary")),
    /** Describe only these tools. Only builds that declare the toolIndex capability accept this. */
    tools: Schema.optionalKey(Schema.Array(Schema.NonEmptyString)),
    /**
     * Describe only declared operations that have schedules, without dynamic tool discovery.
     * Only builds that declare the scheduledTools capability accept this.
     */
    scheduled: Schema.optionalKey(Schema.Literal(true)),
  }),
  Schema.Struct({
    operation: Schema.Literal("skills"),
    /** Answer with SkillSources. Only builds that declare the skillSources capability accept this. */
    sources: Schema.optionalKey(Schema.Literal(true)),
  }),
  Schema.Struct({
    operation: Schema.Literal("query"),
    name: Schema.NonEmptyString,
    input: JsonValue,
  }),
  Schema.Struct({
    operation: Schema.Literal("mutate"),
    name: Schema.NonEmptyString,
    input: JsonValue,
  }),
  Schema.Struct({
    operation: Schema.Literal("call"),
    tool: Schema.NonEmptyString,
    input: JsonValue,
  }),
]);
/** Parsed portable dispatch request. */
export type HostRequest = typeof HostRequest.Type;

/** The dispatch request did not match the protocol. */
export class HostRequestInvalid extends Schema.TaggedError<HostRequestInvalid>()(
  "HostRequestInvalid",
  {},
) {}
/** Host-supplied accounts did not satisfy the declared slots or native method schemas. */
export class HostAccountsInvalid extends Schema.TaggedError<HostAccountsInvalid>()(
  "HostAccountsInvalid",
  {},
) {}
/** The module or declared capability shape could not be hosted. */
export class HostDeclarationInvalid extends Schema.TaggedError<HostDeclarationInvalid>()(
  "HostDeclarationInvalid",
  {},
) {}
/** Fresh app evaluation failed before calling a tool. */
export class HostEvaluationFailed extends Schema.TaggedError<HostEvaluationFailed>()(
  "HostEvaluationFailed",
  {},
) {}
/** No query or mutation matched the requested name. */
export class HostOperationNotFound extends Schema.TaggedError<HostOperationNotFound>()(
  "HostOperationNotFound",
  {},
) {}
/** An app operation failed. Raw author failures remain private. */
export class HostOperationFailed extends Schema.TaggedError<HostOperationFailed>()(
  "HostOperationFailed",
  {},
) {}
/** The freshly evaluated catalog did not contain the requested tool. */
export class HostToolNotFound extends Schema.TaggedError<HostToolNotFound>()(
  "HostToolNotFound",
  {},
) {}
/** One failing input location and its expected shape; never the supplied value. */
export const InputProblem = Schema.String.check(Schema.isMaxLength(512));
/** Input decoding reports at most this many problems. */
export const maxInputProblems = 10;
/** Native input decoding failed; supplied values are omitted. Builds before problems were reported send none. */
export class HostInputInvalid extends Schema.TaggedError<HostInputInvalid>()("HostInputInvalid", {
  problems: Schema.optionalKey(
    Schema.Array(InputProblem).check(Schema.isMaxLength(maxInputProblems)),
  ),
}) {}
/** The tool's approval policy blocked this call before its tool body ran. */
export class HostToolBlocked extends Schema.TaggedError<HostToolBlocked>()("HostToolBlocked", {}) {}
/** Policy elicitation plus decoded input. No tool body ran; the host owns delivery and resumption. */
export class HostToolApprovalRequired extends Schema.TaggedError<HostToolApprovalRequired>()(
  "HostToolApprovalRequired",
  { input: JsonValue, elicitation: ApprovalElicitation },
) {}
/** The tool's approval policy failed or returned an invalid decision. Author failures remain private. */
export class HostToolPolicyFailed extends Schema.TaggedError<HostToolPolicyFailed>()(
  "HostToolPolicyFailed",
  {},
) {}
/** A tool result was not JSON; the result is never included in the error. */
export class HostOutputInvalid extends Schema.TaggedError<HostOutputInvalid>()(
  "HostOutputInvalid",
  {},
) {}

/** Safe error envelope; no author exception, source, account fields or stack is serialized. */
export const HostError = Schema.Union([
  OpenapiResponseError,
  ProviderError,
  McpError,
  SkillLoadFailed,
  WorkflowFailure,
  HostRequestInvalid,
  HostAccountsInvalid,
  HostDeclarationInvalid,
  HostEvaluationFailed,
  HostOperationNotFound,
  HostOperationFailed,
  HostToolNotFound,
  HostInputInvalid,
  HostOutputInvalid,
  HostToolBlocked,
  HostToolApprovalRequired,
  HostToolPolicyFailed,
  ElicitationFailed,
]);
/** Expected host failures. */
export type HostError = typeof HostError.Type;

/** Portable response envelope; callers parse the success value for their operation. */
export const HostResponse = Schema.Union([
  Schema.Struct({
    ok: Schema.Literal(true),
    value: JsonValue,
    toolError: Schema.optionalKey(Schema.Literal(true)),
  }),
  Schema.Struct({ ok: Schema.Literal(false), error: HostError }),
]);
/** Parsed response envelope. */
export type HostResponse = typeof HostResponse.Type;

/**
 * The JSON body the host sends to a bundle's generated server entry. The entry is compiled into
 * the retained build, so this shape is frozen with the protocol too.
 */
export const HostInvocation = Schema.Struct({
  command: HostRequest,
  accounts: ResolvedAccounts,
  approval: Schema.optionalKey(TrustedToolApproval),
  replay: Schema.optionalKey(WorkflowReplay),
  deadline: Schema.optionalKey(InvocationDeadline),
  workflowRun: Schema.optionalKey(WorkflowRunId),
});
export type HostInvocation = typeof HostInvocation.Type;

/** Every message of protocol 1, in the order its snapshot records them. */
export const protocol1 = {
  version: 1,
  schemas: {
    invocation: HostInvocation,
    request: HostRequest,
    response: HostResponse,
    requirements: DeclaredRequirements,
    tools: Schema.Array(HostedTool),
    toolSummaries: Schema.Array(HostedToolSummary),
    skills: SkillCatalogResponse,
    elicitationRequest: FormElicitation,
    elicitationReply: ElicitationReply,
    workflowStep: WorkflowRpcCommand,
    workflowStepReply: WorkflowRpcResult,
    workflowControl: WorkflowControlCommand,
    cacheCommand: CacheCommand,
    cacheReply: CacheReply,
  },
} as const;
