/**
 * Host protocol 3: protocol 2 plus the app's own failure detail. Operation, evaluation and
 * declaration failures carry the error name and bounded, secret-free message the app raised, and
 * workflow failures carry the failing step and app error. Queries and mutations that exceed a
 * database budget, and declarations with a reserved database field, fail with their named error.
 *
 * This protocol is released and frozen once merged. `bun run check` compares `protocol3` with
 * `packages/apps/protocols/3.json`. Do not edit this file or the schemas it reaches to change the
 * wire format; define the next protocol instead. See notes/apps-publishing.md.
 */
import { Schema } from "effect";
import { CacheCommand, CacheReply } from "@executor-js/app-cache/contracts";
import { DatabaseFieldReserved, DatabaseLimitExceeded } from "@executor-js/app-data/contracts";
import { OpenapiResponseError } from "../api-response-error.ts";
import { ElicitationFailed, ElicitationReply, FormElicitation } from "../elicitation.ts";
import { FailureCode, FailureMessage, FailureName, FailureSource } from "../failure.ts";
import { JsonValue } from "../schema.ts";
import { SkillLoadFailed } from "../skills.ts";
import {
  WorkflowControlCommand,
  WorkflowFailure,
  WorkflowRpcCommand,
  WorkflowRpcResult,
} from "../workflows.ts";
import {
  DeclaredRequirements,
  HostAccountsInvalid,
  HostedTool,
  HostedToolSummary,
  HostInputInvalid,
  HostInvocation,
  HostOperationNotFound,
  HostOutputInvalid,
  HostRequest,
  HostRequestInvalid,
  HostToolApprovalRequired,
  HostToolBlocked,
  HostToolNotFound,
  HostToolPolicyFailed,
  McpError,
  ProviderError,
} from "./1.ts";
import { SkillCatalogResponse } from "./2.ts";

/** Protocol 3's failure detail, as released: the app error's source, name, code and message. */
const FailureDetail = {
  source: Schema.optionalKey(FailureSource),
  errorName: Schema.optionalKey(FailureName),
  code: Schema.optionalKey(FailureCode),
  message: Schema.optionalKey(FailureMessage),
};

export {
  DeclaredAuthMethod,
  DeclaredProvider,
  DeclaredRequirements,
  ResolvedAccount,
  ResolvedAccounts,
  TrustedToolApproval,
  InvocationDeadline,
  HostedTool,
  HostedToolSummary,
  HostRequest,
  HostRequestInvalid,
  HostAccountsInvalid,
  HostOperationNotFound,
  HostToolNotFound,
  InputProblem,
  maxInputProblems,
  HostInputInvalid,
  HostToolBlocked,
  HostToolApprovalRequired,
  HostToolPolicyFailed,
  HostOutputInvalid,
  HostInvocation,
} from "./1.ts";
export { SkillSources, SkillCatalogResponse } from "./2.ts";

/**
 * The module or declared capability shape could not be hosted. The detail names what the app
 * declared wrongly; declarations bind no accounts.
 */
export class HostDeclarationInvalid extends Schema.TaggedError<HostDeclarationInvalid>()(
  "HostDeclarationInvalid",
  FailureDetail,
) {}
/** Fresh app evaluation failed before calling a tool. */
export class HostEvaluationFailed extends Schema.TaggedError<HostEvaluationFailed>()(
  "HostEvaluationFailed",
  FailureDetail,
) {}
/** An app operation failed. Carries the app's own error name and bounded, secret-free message. */
export class HostOperationFailed extends Schema.TaggedError<HostOperationFailed>()(
  "HostOperationFailed",
  FailureDetail,
) {}

/**
 * Safe error envelope. Author failures carry only their name and bounded message with account
 * secrets replaced; no source, account fields, stack or cause value is serialized.
 */
export const HostError = Schema.Union([
  OpenapiResponseError,
  ProviderError,
  McpError,
  SkillLoadFailed,
  WorkflowFailure,
  HostRequestInvalid,
  HostAccountsInvalid,
  HostDeclarationInvalid,
  HostEvaluationFailed,
  HostOperationNotFound,
  HostOperationFailed,
  DatabaseLimitExceeded,
  DatabaseFieldReserved,
  HostToolNotFound,
  HostInputInvalid,
  HostOutputInvalid,
  HostToolBlocked,
  HostToolApprovalRequired,
  HostToolPolicyFailed,
  ElicitationFailed,
]);
/** Expected host failures. */
export type HostError = typeof HostError.Type;

/** Portable response envelope; callers parse the success value for their operation. */
export const HostResponse = Schema.Union([
  Schema.Struct({
    ok: Schema.Literal(true),
    value: JsonValue,
    toolError: Schema.optionalKey(Schema.Literal(true)),
  }),
  Schema.Struct({ ok: Schema.Literal(false), error: HostError }),
]);
/** Parsed response envelope. */
export type HostResponse = typeof HostResponse.Type;

/** Every message of protocol 3, in the order its snapshot records them. */
export const protocol3 = {
  version: 3,
  schemas: {
    invocation: HostInvocation,
    request: HostRequest,
    response: HostResponse,
    requirements: DeclaredRequirements,
    tools: Schema.Array(HostedTool),
    toolSummaries: Schema.Array(HostedToolSummary),
    skills: SkillCatalogResponse,
    elicitationRequest: FormElicitation,
    elicitationReply: ElicitationReply,
    workflowStep: WorkflowRpcCommand,
    workflowStepReply: WorkflowRpcResult,
    workflowControl: WorkflowControlCommand,
    cacheCommand: CacheCommand,
    cacheReply: CacheReply,
  },
} as const;
